### PR TITLE
1.4 Redirect from CP Home to DashEE

### PR DESCRIPTION
**Pull request by GDmac**
Updated the extension to redirect from CP Home to DashEE.

To install, disable and Enable DashEE extension only.
(no need for update method bagage)

The sessions_end method includes some checks that the user has access to the module.
Can you verify this all works as planned?

### CODE REVIEW

**Comment by mrtopher** [comment]
Thanks for taking a swing at this GDmac!

Couple of problems while I was testing this though...
- need to eliminate the class variable base_url because the BASE constant is not assigned yet when session_end is called thereby throwing a warning. I moved the creation of the URL into the individual methods where it's needed and that solved that problem.
- in the session_end method, the "assigned_modules" array is blank for my super admin user thereby causing an undefined index error.
- also in the session_end method, you are referencing an "admin_session_type" index that doesn't exist in the $data->userdata array at all from what I can see.

Even after commending a majority of the code out I'm still getting weird errors like "Message: Undefined property: Homepage::$session Filename: libraries/Functions.php Line Number: 368" when trying to redirect the user.

**Comment by GDmac** [comment]
changes
- only set base_url if BASE is defined
- admin_session_type is in EE->config (_cough_)
- redirecting with header() instead of functions library

**Comment by mrtopher** [comment]
Yep, I was running a version or two behind... sorry.

This is looking good, just need to make a tweak here and there and should be good. 

Should have it merged in the next day or two. Then I'll take a look at your other request.

Thanks for the help!

**Comment by GDmac** [comment]
I'll force push-update tomorrow, since this->base_url is now also valid for sessions_end. I'll also incorporate the fix in the other pull-req so asap after that.

**Pull request closed without merging**
